version: '2'
services:
    sportplacereservation-app:
        image: sportplacereservation
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sportplacereservation-postgresql:5432/SportPlaceReservation
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sportplacereservation-postgresql:
        extends:
            file: postgresql.yml
            service: sportplacereservation-postgresql
